language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: dachfest-8ec02 
  token:
    secure: "2KyemurWw35tbkUtq3S4IZ3V8wR7Zjfzz31unWRAFh/+FqQJVRTlMWKQ4EnqnXmM2fs9scMYXkFhSO8Pwic4XaTqguEvhX4wu1a9QecKqiMZHOuzWaZBAqsEWOyRdNdPQhCb95qgeY+YV9ijnWmTXWO6iw9345mcCOloe8pyuxaS61Ll9L8oO7KGXI3fNymc/17HxDg1EuAnDE504zzTpgl5ucok2EcXhN65uv7gaHj8BOc6zAONeCt9gtuA0pDpV/5fUvI5UDdFtkYSSNgtkeabUixTsBYFqnj8Yt23vl4wJTAAy2kVV1GCGJyKqfm3UzeN1+JR/8mHaukUNierJftVoQfCwlwWkHwc+DpOUy81RnRL4/xbOTGhRI84f/R83rfo9SRRlLBi+W955sVP3CHrg1rrTf8y7PtpLy+Eojq2xFvkfiSKy1eYY08q6ztqRzG7djAZr7me4UpcoImyaC3NMzI4gwABIhbO31satNUpIIyAz3qcefJ1Vfrqc+slPdvsvaGeQE0ika000YWZWZYhB0GFRYQW7oQUJOmAYYK5DmI5mqaPMWW5WNvFmsreydEIQVEnoc/V9N8Q4HV1NRIwGjJDUEfmBeQ6eWYH7rVD2E5XxtcAM7foaMpz+9T+v2CNA3d2bcCQXElzkdG3TXbZ1kKoWiTiI4HHAUnQcnA="
