language: node_js
node_js: 8
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
install:
- yarn
- cd functions && yarn && cd ..
script:
- yarn lint
- echo "Building..."
- if [ "$TRAVIS_BRANCH" == "develop" ]; then yarn build; fi
- if [ "$TRAVIS_BRANCH" == "master" ]; then yarn build:prod; fi
before_deploy:
- echo "Deploying!"
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: dachfest-8ec02 
  token:
    secure: "NGW4Hv/qKpJ9w8K06XrXwRyvY3eLd12+97zBey2AKmJvlw6sE5fvsm8o7Zawz5GJOeTcPn0n7d4T9c4QR7aoW5eU+zieRSmj13G+KUi4HVbEl/lIwhECSL81Q0tE9eJhPb9zpu07lKSQqeEXil4HnlVq2PeTeb1HNiuksc60Puxl47EdyFsmuxjXpRYFds6rfPZBzaCNiUSS+D7lMLnmogumTNbw8BBG4qlF5voaqyvWFlw7qn3BL3RMZXKs7/3pF23yHakwzNLZPa6XidZZQ7cobQjeFl7NXZCLzkHzJovRzPBw4LxWJBMu55e8sfN9rrms0+u39Xf5+iVt/HiVEu7ca8lTJv/YLTvnM1Bcls6tNzY0BP79F+NPHzaadwmWfut4o6HN2hQNwzmwLBV3WtYyQdxgHim5qo4Q6geUhHK1R5JMk7aGKewgwqVOgdBmgkPGzMoxtVCnihDCMLRdBmYIBgWJmTSeEDaq5HnWmX61YQ4ztraDkQ8w97tBrXXjH0hXUFpPrmywcoet3++vxWKudff0Hx3LDzr/e2mFre5GJNRT6fEZKv5FRFfDeUdOAvUopStWLONyAnptyP6816CpwoxwprKDSkmBD+E7M+WAQfUkQY7x3l4Q2GIEDqFDj7zy5pNPYMquhLN7etST4rAcQhsuqG9Yte4FRHCIDHU="
